version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: simple_flask_api
    restart: always
    ports:
      - "5000:5000"
    tty: true
    depends_on:
      - postgres
    networks:
      - fullstack
  postgres:
    image: postgres:12.1
    container_name: postgres
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_DB: 'simple_api'
    ports:
      - 5433:5432
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge